runtime: nodejs18

handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /cmaps
    static_dir: public/cmaps

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
